<?php
/**
 * Created by PhpStorm.
 * User: stepanov
 * Date: 11.08.2016
 * Time: 10:42
 */

namespace MacGruber11\ff_model\model;

use Illuminate\Database\Eloquent\Model as Model;

class FFModel extends Model
{
    protected $abilities = [];

    public function __construct(array $attributes)
    {
        parent::__construct($attributes);
    }

    public function save(array $options = [])
    {
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}